---
      - name: install mySQL
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - mysql-server
          - python-mysqldb

      - name: ensure mysqld group is present
        lineinfile: dest=/etc/mysql/my.cnf line=[mysqld] state=present
        notify: restart mysql

      - name: ensure mySQL listenig on all ports
        lineinfile: dest=/etc/mysql/my.cnf insertafter=^[mysqld] regexp=^bind-address line="bind-address = {{ ansible_eth0.ipv4.address }}"
        notify: restart mysql

      - name: ensure mySQL started
        service: name=mysql state=started enabled=yes

      - name: create DB
        mysql_db: name= {{ db_name }} state=present

      - name: add DB user
        mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL host='{{ db_user_host }}' state=present
