---
# Stop stack
  - hosts: lb
    tasks:
      -  service: name=nginx state=stopped
      -  wait_for: port=80 state=drained

  - hosts: web
    tasks:
      -  service: name=apache2 state=stopped
      -  wait_for: port=80 state=stopped

# Reboot DB
  - hosts: db
    tasks:
      -  service: name=mysql state=restarted
      -  wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 state=started

# Bring stack up
  - hosts: web
    tasks:
      -  service: name=apache2 state=started
      -  wait_for: port=80 state=started

  - hosts: lb
    tasks:
      -  service: name=nginx state=started
      -  wait_for: port=80 state=started
