---
  - hosts: lb
    become: true
    tasks:
      - name: verify nginx service
        command: service nginx status

      - name: verify nginx port
        wait_for: port=80 timeout=1

  - hosts: web
    become: true
    tasks:
      - name: verify apache2 service
        command: service apache2 status

      - name: verify apache2 port
        wait_for: port=80 timeout=1

  - hosts: db
    become: true
    tasks:
      - name: verify mysql service
        command: service mysql status

      - name: verify mysql port
        wait_for: port=3306 timeout=1

  - hosts: lb
    tasks:
      - name: verify backends response
        uri: url=http://app01 return_content=yes
        #with_items: groups.web
        register: web_index

      - fail: msg="index failed to return content"
        when: "'Hello, from sunny' not in web_index.content"
        #with_items: "{{web_index.results}}"
